name = "uscis-api-worker"
main = "uscis-worker.js"
compatibility_date = "2024-01-01"

# Set your Cloudflare account ID here
account_id = "db31d46fbe58cf65032aef4514f91fa0"

# Domain routing will be configured after deployment
# For now, the worker will be available at: https://uscis-api-worker.your-subdomain.workers.dev
# routes = [
#   { pattern = "uscis.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Environment variables (set these in Cloudflare dashboard)
[vars]
# These will be set in Cloudflare dashboard, not here
# USCIS_CLIENT_ID = "your_client_id"
# USCIS_CLIENT_SECRET = "your_client_secret"

# Optional: Set to true for development
[env.development]
name = "uscis-api-worker-dev" 